version: '3.8'
services:
  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 3000:3000
    volumes:
      - ./data/plugins:/usr/src/redmine/plugins
      - ./data/themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: redmine
    depends_on:
      - redmine-db
    restart: always

  redmine-db:
    image: mariadb
    container_name: redmine-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      - ./data/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always

  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - 80:80
      - 443:443
    links:
      - redmine
    restart: always
    environment:
      DOMAINS: 'redmine.unitedtg.co.jp -> http://redmine.unitedtg.co.jp:3000'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal
